---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False

  vars:
      region: eu-central-1
      instance_type: t2.micro
      ami: ami-05f7491af5eef733a   # Ubuntu 20.04 LTS
      keypair: vova-key # pem file name
#      subnetid: subnet-0e80c6bbb664c7138
      project_name: hw13
  
  tasks:
    - name: Create security group
      ec2_group:
       name: "{{ project_name }}_security_group"
       description: "{{ project_name }} security group"
       region: "{{ region }}"
       rules:
         - proto: tcp  # ssh
           from_port: 22
           to_port: 22
           cidr_ip: 0.0.0.0/0
         - proto: tcp  # http
           from_port: 80
           to_port: 80
           cidr_ip: 0.0.0.0/0
         - proto: tcp  # https
           from_port: 443
           to_port: 443
           cidr_ip: 0.0.0.0/0
       rules_egress:
         - proto: all
           cidr_ip: 0.0.0.0/0
    

  - name: Create an ec2 instance
    ec2:
      key_name: "{{ keypair }}"
      group: "{{ project_name }}_security_group"  # security group name
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: true
      region: "{{ region }}"
      count: 1  # default
      count_tag:
        Name: Demo
      instance_tags:
        Name: Demo
      assign_public_ip: yes
    register: ec2