---
- name: Create a new Demo EC2 instance
  hosts: localhost
  gather_facts: False
  roles:
    - create

- name: Prepare instance
  hosts: ec2_hosts
  gather_facts: False
  become: yes
  roles:
    - prepair

- name: Build app
  hosts: build
  become: yes
  roles:
    - build

- name: run app
  hosts: prod
  become: yes
  roles:
    - prod