---
- name: Create an ec2 instance
  ec2:
    key_name: "{{ project_name }}-key"
    group: "{{ project_name }}_security_group"  # security group name
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    id: "{{ project_name }}-{{item}}"
    wait: true
    region: "{{ region }}"
    count: 1  # default
    vpc_subnet_id: subnet-09c48563
    count_tag:
      Name: "{{item}}"
    instance_tags:
      Name: "{{item}}"
    assign_public_ip: yes
  register: ec2

- name: Print all available facts
  ansible.builtin.debug:
    var: ec2.instances.public_ip

#- name: Add IP to ec2_hosts group
#  add_host: 
#    hostname: "{{ ec2.instances.public_ip }}" 
#    groups:
#      - ec2_hosts 
#      - "{{item}}"