---
- name: Create an ec2 instance
  ec2:
    key_name: "{{ project_name }}-key"
    group: "{{ project_name }}_security_group"  # security group name
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    id: "{{ project_name }}-{{item}}-8"
    wait: true
    wait_timeout: 500
    region: "{{ region }}"
    count: 1  # default
    vpc_subnet_id: subnet-09c48563
    count_tag:
      Name: "{{item}}"
    instance_tags:
      Name: "{{item}}"
    assign_public_ip: yes
  register: ec2

- name: Add IP to  groups
  add_host:
    hostname: "{{ ec2.instances[0].public_ip }}"
    ansible_user: ubuntu
    ansible_ssh_private_key_file: "/opt/aws-private-{{item}}.pem"
    groups:
      - ec2_hosts
      - "{{item}}"
#  with_items: "{{ec2.instances}}"
#  loop_control:
#    loop_var: item1
