---
- name: Create an EC2 key
  ec2_key:
    name: "{{ project_name }}-key"
    region: "{{ region }}"
  register: ec2_key

- name: Save private key
  copy: 
    content: "{{ ec2_key.key.private_key }}" 
    dest: "/aws-private.pem" 
    mode: 0600
  when: ec2_key.changed
    
- name: Create security group
  ec2_group:
    name: "{{ project_name }}_security_group"
    description: "{{ project_name }} security group"
    region: "{{ region }}"
    rules:
      - proto: tcp  # ssh
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      - proto: tcp  # http
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp  # https
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
 
- name: Create an ec2 instance and add to hosts
  include_tasks: create_ec2.yml 
  loop: "{{name_instance}}"
  
