---
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
    
- name: install Docker
  apt:  name={{ packages }} state=present update_cache=yes
   

- name: Check services
  service: name={{ services }} state=started